return {
  "CreateFrame",
  "UIParent",
  "GetPhysicalScreenSize",
  "PixelUtil",
  "PlaySoundFile",
  "StopSound",
  "C_AddOns",
  "C_Timer",
  "time",
  "GetServerTime",
  "debugprofilestop",
  "GetTime",
  "GetBuildInfo",
}
